server:
  port: 8081
hm:
  db:
    host: 192.168.153.129 # 修改为你自己的虚拟机IP地址
    pw: 123 # 修改为docker中的MySQL密码
    port: 3307
    database: hm-item

  swagger:
    title: 黑马商城商品接口管理
    desc: "黑马商城商品接口管理"
    package: com.hmall.item.controller
